name: Tests2

on: [push,pull_request]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    # Setup a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.2'
        channel: 'stable'
    - name: Install Dependencies
      working-directory: ./flutter_bloc_sample
      run: flutter pub get
    # run static analys code
    - name: Run static analys code
      working-directory: ./flutter_bloc_sample
      run: flutter analyze
    # run  flutter widgets tests  and unit tests
    - name: Run tests
      working-directory: ./flutter_bloc_sample
      run: flutter test --coverage
    # Upload coverage reports to Codecov
    # https://github.com/marketplace/actions/codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
